# Generated by Django 2.0.5 on 2018-05-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=250)),
                ('bitcoin_value', models.DecimalField(decimal_places=8, max_digits=70)),
                ('status', models.BooleanField(default=False)),
                ('time_matched', models.DateTimeField(auto_now_add=True)),
                ('time_completed', models.DateTimeField(null=True)),
                ('expiry_data', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evidences',
            name='for_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Match'),
        ),
    ]
