# Generated by Django 2.0.5 on 2018-05-13 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180513_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='expiry_data',
        ),
        migrations.AddField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 10, 38, 45, 719370, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Completed', 'Completed'), ('Waiting', 'Waiting')], default='Waiting', max_length=200),
        ),
    ]
