# Generated by Django 2.0.5 on 2018-05-15 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180513_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='grace',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 5, 15, 0, 823706, tzinfo=utc)),
        ),
    ]
