# Generated by Django 2.0.5 on 2018-05-15 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180515_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='maturity_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 10, 11, 10, 871535, tzinfo=utc)),
        ),
    ]
