# Generated by Django 2.0.5 on 2018-05-15 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180515_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='completed',
        ),
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(default='Awaiting Payment', max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 15, 11, 57, 506229, tzinfo=utc)),
        ),
    ]
