# Generated by Django 2.0.5 on 2018-05-15 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180515_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='bitcoin_value',
            field=models.DecimalField(decimal_places=8, max_digits=70, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 15, 32, 24, 812880, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Completed', 'Completed'), ('Waiting For Match', 'Waiting For Match'), ('Waiting For Payment', 'Waiting For Payment')], default='Waiting', max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='time_matched',
            field=models.DateTimeField(null=True),
        ),
    ]
