# Generated by Django 2.0.5 on 2018-05-16 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180515_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 5, 21, 44, 62445, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Completed', 'Completed'), ('Waiting For Match', 'Waiting For Match'), ('Waiting For Payment', 'Waiting For Payment')], default='Waiting For Match', max_length=200),
        ),
    ]
