# Generated by Django 2.0.5 on 2018-05-16 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180516_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_name',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 15, 35, 30, 525097, tzinfo=utc), null=True),
        ),
    ]
