# Generated by Django 2.0.5 on 2018-05-16 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180516_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='created_name',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 15, 35, 54, 956005, tzinfo=utc), null=True),
        ),
    ]
