# Generated by Django 2.0.5 on 2018-05-18 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20180516_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='receiver',
        ),
        migrations.AddField(
            model_name='match',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='dashboard.Investment'),
        ),
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 9, 59, 2, 648379, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Awaiting Match', max_length=200),
        ),
    ]
