# Generated by Django 2.0.5 on 2018-05-18 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20180518_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 10, 3, 43, 417159, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='dashboard.Plan'),
        ),
    ]
